language: c
sudo: false
os:
- linux
- osx
env:
  matrix:
  - CHASKEY_ROUNDS=8
  - CHASKEY_ROUNDS=12
before_script:
- CFLAGS=(-Wall -DCHASKEY_ROUNDS=$CHASKEY_ROUNDS -DCHASKEY_TEST=1 -DCHASKEY_DEBUG=1)
- gcc "${CFLAGS[@]}" chaskey.c -o chaskey
script:
- ./chaskey
